1 let nome = prompt("digite seu nome: ")
2 let idade = Number(prompt("digite sua idade: "))
3 let email = (prompt("digite seu email: "))
4 let telefone = Number(prompt("digite seu numero de telefone: "))
5 console.log("Seu nome é", nome, "você tem", idade, "anos", "o seu email é", email, "e para finalizar, seu numero de telefone é", telefone)




1 let ano = Number(prompt("Digite a seu ano de nascimento: "))
2 let atual = 2025
3 console.log("Você tem", (atual - ano), "anos")